"""Wrap the Caddy admin API: low-level config primitives, plus opinionated recipes for TLS and reverse-proxy routes

Docs: https://AnswerDotAI.github.io/fastcaddy/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['admin_url', 'default_admin', 'get_id', 'get_path', 'gid', 'has_id', 'gcfg', 'has_path', 'pid', 'pcfg', 'reset',
           'del_id', 'automation_path', 'srvs_path', 'rts_path', 'CaddyAdmin', 'nested_setdict', 'path2keys',
           'keys2path', 'nested_setcfg', 'init_path', 'get_acme_config', 'add_tls_internal_config', 'add_acme_config',
           'caddy_docs', 'get_schema', 'search_schema', 'init_routes', 'setup_pki_trust', 'setup_caddy',
           'encode_handler', 'proxy_handler', 'add_route', 'add_reverse_proxy', 'add_on_demand_tls',
           'add_wildcard_route', 'add_sub_route', 'add_sub_reverse_proxy']

# %% ../nbs/00_core.ipynb #4efe69d2
import os, httpx, json
from fastcore.utils import *
from httpx import HTTPStatusError, ConnectError, get as xget, delete as xdelete
from typing import Sequence

# %% ../nbs/00_core.ipynb #7a064803
admin_url = os.environ.get('CADDY_ADMIN', 'http://localhost:2019')

# %% ../nbs/00_core.ipynb #caddyadmincls
class CaddyAdmin:
    "Drive one Caddy admin API. The module-level functions are bound methods of a default instance."
    def __init__(self,
        url=None, # Admin API base URL (defaults to the `admin_url` global, i.e. `$CADDY_ADMIN`)
        client=None): # httpx client (inject one with a mock transport for tests)
        self._url,self._client = url,client

    @property
    def url(self): return self._url or admin_url
    @property
    def client(self):
        if self._client is None: self._client = httpx.Client()
        return self._client

# %% ../nbs/00_core.ipynb #caddyadmininst
default_admin = CaddyAdmin()

# %% ../nbs/00_core.ipynb #p_getid
@patch
def get_id(self:CaddyAdmin, path):
    "Get an ID full URL from a path"
    if path[0]!='/': path = '/'+path
    if path[-1]!='/': path = path+'/'
    return f'{self.url}/id{path}'

# %% ../nbs/00_core.ipynb #p_getpath
@patch
def get_path(self:CaddyAdmin, path):
    "Get a config full URL from a path"
    if path[0]!='/': path = '/'+path
    if path[-1]!='/': path = path+'/'
    return f'{self.url}/config{path}'

# %% ../nbs/00_core.ipynb #p_req
@patch
def _req(self:CaddyAdmin, method, url, **kw):
    "Request `url` via `method`, raising errors enriched with caddy's detail; returns the response"
    try: response = self.client.request(method, url, **kw)
    except ConnectError as e:
        e.add_note(f"Could not reach the caddy admin API at {self.url} -- is caddy running?")
        raise
    try: response.raise_for_status()
    except HTTPStatusError as e:
        try: msg = json.loads(response.text)['error']
        except Exception: msg = response.text
        if msg: e.add_note(f"Error: '{msg}'")
        raise
    return response

# %% ../nbs/00_core.ipynb #p_gid
@patch
def gid(self:CaddyAdmin, path='/'):
    "Get the config object whose `@id` matches `path`"
    return dict2obj(self._req('GET', self.get_id(path)).json())

# %% ../nbs/00_core.ipynb #p_hasid
@patch
def has_id(self:CaddyAdmin, id):
    "Check if `id` is set up"
    try: self.gid(id)
    except HTTPStatusError: return False
    return True

# %% ../nbs/00_core.ipynb #p_gcfg
@patch
def gcfg(self:CaddyAdmin, path='/'):
    "Get the config at `path`"
    return dict2obj(self._req('GET', self.get_path(path)).json())

# %% ../nbs/00_core.ipynb #p_haspath
@patch
def has_path(self:CaddyAdmin, path):
    "Check if any config exists at `path`"
    try: return self.gcfg(path) is not None
    except HTTPStatusError: return False

# %% ../nbs/00_core.ipynb #p_pid
@patch
def pid(self:CaddyAdmin, d, path='/', method='POST'):
    "Put/post config `d` to the object whose `@id` matches `path`"
    return self._req(method, self.get_id(path), json=obj2dict(d)).text or None

# %% ../nbs/00_core.ipynb #p_pcfg
@patch
def pcfg(self:CaddyAdmin, d, path='/', method='POST'):
    "Put/post config `d` at `path`"
    return self._req(method, self.get_path(path), json=obj2dict(d)).text or None

# %% ../nbs/00_core.ipynb #p_reset
@patch
def reset(self:CaddyAdmin):
    "Erase the entire caddy config"
    return self.pcfg({})

# %% ../nbs/00_core.ipynb #p_delid
@patch
def del_id(self:CaddyAdmin, id):
    "Delete every config object whose `@id` matches `id` (e.g. a host)"
    while self.has_id(id): self._req('DELETE', self.get_id(id))

# %% ../nbs/00_core.ipynb #caddyadminbind
get_id,get_path,gid,has_id,gcfg,has_path,pid,pcfg,reset,del_id = (
    default_admin.get_id, default_admin.get_path, default_admin.gid, default_admin.has_id,
    default_admin.gcfg, default_admin.has_path, default_admin.pid, default_admin.pcfg,
    default_admin.reset, default_admin.del_id)

# %% ../nbs/00_core.ipynb #51350dcd
def nested_setdict(sd, value, *keys):
    "Returns `sd` updated to set `value` at the path `keys`"
    d = sd
    for key in keys[:-1]: d = d.setdefault(key, {})
    d[keys[-1]] = value
    return sd

# %% ../nbs/00_core.ipynb #5690527d
def path2keys(path):
    "Split `path` by '/' into a list"
    return path.strip('/').split('/')

# %% ../nbs/00_core.ipynb #e8a5fd7b
def keys2path(*keys):
    "Join `keys` into a '/' separated path"
    return '/'+'/'.join(keys)

# %% ../nbs/00_core.ipynb #a4213aca
def nested_setcfg(value, *keys):
    "Set `value` at the path `keys` in the live caddy config"
    d = nested_setdict(gcfg(), value, *keys)
    return pcfg(d)

# %% ../nbs/00_core.ipynb #c00a6147
def init_path(path):
    "Create `path` (and any missing parents) as an empty object, if not already present"
    if not has_path(path): pcfg({}, path, method='put')

# %% ../nbs/00_core.ipynb #692a979c
automation_path = '/apps/tls/automation'
def get_acme_config(token):
    "An ACME issuer config using cloudflare DNS challenges with `token`"
    prov = { "provider": { "name": "cloudflare", "api_token": token } }
    return { "module": "acme", "challenges": { "dns": prov } }

# %% ../nbs/00_core.ipynb #f6a4a122
def add_tls_internal_config():
    "Set up a TLS automation policy using caddy's internal CA, if no automation config exists yet"
    if has_path(automation_path): return
    init_path(automation_path)
    pcfg([{"issuers": [{"module": "internal"}]}], automation_path+'/policies')

# %% ../nbs/00_core.ipynb #3d726b65
def add_acme_config(cf_token, subjects=None):
    "Set up a TLS automation policy using ACME with cloudflare DNS challenges, if no automation config exists yet"
    if has_path(automation_path): return
    if not cf_token: raise ValueError("`cf_token` is required for ACME config")
    init_path(automation_path)
    policy = {'issuers': [get_acme_config(cf_token)]}
    if subjects: policy['subjects'] = subjects
    pcfg([policy], automation_path+'/policies')

# %% ../nbs/00_core.ipynb #d1459604
_caddy_docs = None

def caddy_docs():
    "The caddy JSON schema, loaded (once) from the bundled `caddy_schema.json`"
    global _caddy_docs
    if not _caddy_docs:
        pkg = Path(__file__).parent if '__file__' in globals() else Path('../fastcaddy')
        _caddy_docs = loads((pkg/'caddy_schema.json').read_text())
    return _caddy_docs

# %% ../nbs/00_core.ipynb #10179442
def get_schema(path:str):
    "Get the caddy schema node at `path` (e.g. '/definitions/tls/properties/automation' or a path from `search_schema`)"
    node = caddy_docs()
    for part in path.strip('/').split('/'): node = node[int(part[1:-1])] if part.startswith('[') and part.endswith(']') else node[part]
    return node

# %% ../nbs/00_core.ipynb #686ae2fb
def _search_schema(term, d, path='', max_results=20):
    results = []
    if isinstance(d, dict):
        for k, v in d.items():
            p = f"{path}/{k}"
            if term.lower() in k.lower(): results.append(('key', p))
            results.extend(_search_schema(term, v, p, max_results))
    elif isinstance(d, list):
        for i, v in enumerate(d): results.extend(_search_schema(term, v, f"{path}/[{i}]", max_results))
    elif isinstance(d, str) and term.lower() in d.lower(): results.append(('value', path, d[:200]))
    return results[:max_results]

def search_schema(term:str, path:str='', max_results:int=20):
    "Recursively search the caddy schema for keys/values containing `term`; returned paths work with `get_schema`"
    d = get_schema(path) if path else caddy_docs()
    return _search_schema(term, d, path, max_results)

# %% ../nbs/00_core.ipynb #9f2a60df
srvs_path = '/apps/http/servers'
rts_path = srvs_path+'/srv0/routes'

# %% ../nbs/00_core.ipynb #1c24566f
def init_routes():
    "Create the basic http server config (`srv0` on ports 80/443), if no servers exist yet"
    if has_path(srvs_path): return
    init_path(srvs_path)
    ir = dict(listen=[':80', ':443'], routes=[], protocols=['h1', 'h2'])
    pcfg(ir, f"{srvs_path}/srv0")

# %% ../nbs/00_core.ipynb #cce1f220
def setup_pki_trust(install_trust):
    "Configure PKI certificate authority trust installation"
    if install_trust is None: return
    pki_path = '/apps/pki/certificate_authorities/local'
    init_path(pki_path)
    pcfg({"install_trust": install_trust}, pki_path)

# %% ../nbs/00_core.ipynb #1d730861
def setup_caddy(
    cf_token=None, # Cloudflare API token (required unless `local`)
    local:bool=False, # Use caddy's internal CA instead of ACME (for local dev)
    install_trust:bool=None, # Install the local CA into the system trust store?
    subjects=None # Subject names to restrict ACME cert issuance to
):
    "Create TLS automation config and the http server skeleton"
    if local: add_tls_internal_config()
    else: add_acme_config(cf_token, subjects=subjects)
    setup_pki_trust(install_trust)
    init_routes()

# %% ../nbs/00_core.ipynb #f3f9a32b
def encode_handler():
    "An `encode` handler that compresses responses with zstd or gzip"
    enc = {"gzip": {"level": 1}, "zstd": {"level": "fastest"}}
    return dict(handler='encode', encodings=enc, prefer=['zstd', 'gzip'])

# %% ../nbs/00_core.ipynb #d1a22749
def proxy_handler(
    *upstreams, # Upstream dial addresses, e.g. 'localhost:5001'
    st_delay='1m' # Keep streaming connections open this long across config reloads (None to disable)
):
    "A `reverse_proxy` handler dialing `upstreams`"
    res = {"handler": "reverse_proxy", "upstreams": [{"dial": u} for u in upstreams]}
    if st_delay: res["stream_close_delay"] = st_delay
    return res

# %% ../nbs/00_core.ipynb #6e73c647
def add_route(route):
    "Append `route` to `srv0`'s route list"
    return pcfg(route, rts_path)

# %% ../nbs/00_core.ipynb #f3b95e5e
def add_reverse_proxy(from_host, to_url, st_delay='1m', encode:bool=True):
    "Create (or replace) a route reverse-proxying `from_host` to `to_url`, tagged with `@id` `from_host`"
    if has_id(from_host): del_id(from_host)
    res = []
    if encode: res.append(encode_handler())
    res.append(proxy_handler(to_url, st_delay=st_delay))
    add_route({ "handle": res, "match": [{"host": [from_host]}], "@id": from_host, "terminal": True })

# %% ../nbs/00_core.ipynb #78f094d5
def add_on_demand_tls(endpoint):
    "Enable on-demand TLS, asking `endpoint` for permission before each cert is issued"
    init_path(automation_path)
    od_path = automation_path+'/on_demand'
    od = {"permission": {"module": "http", "endpoint": endpoint}}
    pcfg(od, od_path, method='patch' if has_path(od_path) else 'put')
    policies_path = automation_path+'/policies'
    od_policy = {"on_demand": True, "issuers": [{"module": "acme"}]}
    if not has_path(policies_path): pcfg([od_policy], policies_path, method='put')
    else:
        policies = obj2dict(gcfg(policies_path))
        if not any(isinstance(o, dict) and o.get('on_demand') for o in policies):
            policies.append(od_policy)
            pcfg(policies, policies_path, method='patch')

# %% ../nbs/00_core.ipynb #d21091ad
def add_wildcard_route(domain):
    "Add a route matching `*.{domain}` (tagged `wildcard-{domain}`) for subroutes; no-op if it already exists"
    wid = f"wildcard-{domain}"
    if has_id(wid): return
    add_route({"match": [{"host": [f"*.{domain}"]}], "handle": [{"handler": "subroute", "routes": []}], "@id": wid, "terminal": True})

# %% ../nbs/00_core.ipynb #48b382a9
def add_sub_route(domain, route):
    "Append `route` to `domain`'s wildcard subroute list, replacing any existing route with the same `@id`"
    wid = f"wildcard-{domain}"
    if not has_id(wid): raise ValueError(f"No wildcard route for {domain} -- call `add_wildcard_route` first")
    rid = route.get('@id')
    if rid and has_id(rid): del_id(rid)
    pid([route], f"{wid}/handle/0/routes/...")

# %% ../nbs/00_core.ipynb #b30a11df
def add_sub_reverse_proxy(
    domain, # Domain with an existing wildcard route
    subdomain, # Subdomain to proxy (tagged `{subdomain}.{domain}`)
    port:str|int|Sequence, # A single port or list of ports
    host='localhost', # Host the upstream(s) listen on
    st_delay='1m', # Keep streaming connections open this long across config reloads (None to disable)
    encode:bool=True # Compress responses?
):
    "Create (or replace) a reverse proxy to `{subdomain}.{domain}` inside `domain`'s wildcard route"
    route_id = f"{subdomain}.{domain}"
    if isinstance(port, (int,str)): port = [port]
    res = []
    if encode: res.append(encode_handler())
    res.append(proxy_handler(*[f"{host}:{p}" for p in port], st_delay=st_delay))
    add_sub_route(domain, {"@id": route_id, "match": [{"host": [route_id]}], "handle": res})
