name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy with cloudflare plugin
        run: |
          cd ~/go/bin
          ./xcaddy build --with github.com/caddy-dns/cloudflare

      - name: Start caddy for testing
        run: |
          ~/go/bin/caddy run &
          sleep 5  # Give caddy time to start

      - name: Run nbdev tests
        env:
          CLOUDFLARE_API_TOKEN: DUMMY_TOKEN
        uses: fastai/workflows/nbdev-ci@master
        with:
          skip_test: true        

      - name: Stop caddy
        run: pkill caddy

